# Generated by Django 4.0.5 on 2022-06-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=20)),
                ('service_charge', models.IntegerField(blank=True, null=True)),
                ('service_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
