# Generated by Django 4.0.5 on 2022-06-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_service',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
