# Generated by Django 4.0.3 on 2022-06-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_service_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='Gender',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
