# Generated by Django 4.0.3 on 2022-06-27 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customers_gender_services_req_request_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_service',
            name='Diesel',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='add_service',
            name='Petrol',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='services_req',
            name='Mechanic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.mechanic'),
        ),
    ]
