# Generated by Django 4.0.3 on 2022-06-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_service_diesel_add_service_petrol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services_req',
            name='charge',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
