# Generated by Django 4.0.3 on 2022-06-28 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_services_req_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_car_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, null=True)),
                ('service_charge', models.CharField(max_length=100, null=True)),
                ('Srequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.services_req')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customers')),
            ],
        ),
    ]
