# Generated by Django 4.0.3 on 2022-06-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_car_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='add_service',
            name='Diesel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='add_service',
            name='Petrol',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
