# Generated by Django 4.0.3 on 2022-07-11 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_mechanic_salary_alter_add_service_diesel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_charge', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Srequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.services_req')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customers')),
            ],
        ),
    ]
